### ISSUE TITLE
TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by Tombother** [Rubiksman78/RenAI-Chat#10]
I don't know how to solve this error

```
Requirement already satisfied: numpy==1.23.0 in c:\renaichat-1.0-pc\libs\pythonlib\lib\site-packages (1.23.0)

Traceback (most recent call last); 
  File "main.py", line 40, in <module> 
    from chatbot.model import build_model_and_tokenizer_for 
  File "C:\RenAIChat-1.0-pc\chatbot\model.py", line 5, in <module> 
    import transformers 
  File "C:\RenAIChat-1.0-pc\libs\pythonlib\lib\site-packages\transformers\__init__.py", line 30
, in <module> 
    from . import dependency_versions_check 
  File "C:\RenAIChat-1.0-pc\libs\pythonlib\lib\site-packages\transformers\dependency_versions_check.py",
line 17, in <module> 
    from .utils.versions import require_version, require_version_core 
  File "C:\RenAIChat-1.0-pc\libs\pythonlib\lib\site-packages\transformers\utils\___init__.py", 
line 34, in <module> 
    from .generic import (
  File "C:\RenAIChat-1.0-pc\libs\pythonlib\lib\site-packages\transformers\utils\generic.py", 
line 29, in <module> 
    from .import_utils import is_flax_available, is_tf_available, is_torch _available, is_torch_fx_proxy 
  File "C:\RenAIChat-1.0-pc\libs\pythonlib\lib\site-packages\transformers\utils\import_utils.p
y", line 390, in <module> 
    torch_version = version.parse(importlib_metadata.version( "torch")) 
  File "C:\RenAIChat-1.0-pc\libs\pythonlib\lib\site-packages\packaging\version.py", line 52, i
n parse 
    return Version(version) 
  File "C:\RenAIChat-1.0-pe\libs\pythonlib\lib\site-packages\packaging\version.py", line 195, 
in __init__
    match = self._regex.search(version) 
TypeError: expected string or bytes-like object

```

**Comment by Rubiksman78** [comment]
Did you modify the script `main.py`, line 40 should be `from chatbot.model import build_model_and_tokenizer_for` instead of your `from chatbot mode! import build model_and_tokenizer_for `

**Comment by Tombother** [comment]
> Did you modify the script `main.py`, line 40 should be `from chatbot.model import build_model_and_tokenizer_for` instead of your `from chatbot mode! import build model_and_tokenizer_for `

No

**Comment by Rubiksman78** [comment]
Maybe try to run `update.bat` and try again
