### ISSUE TITLE
I found no model to use

### ISSUE THREAD

**Issue by foxmooner** [Rubiksman78/RenAI-Chat#7]
when I use pygmalion1.3b or 2.7b. when i open run.bat
it show 
```
Requirement already satisfied: numpy==1.23.0 in d:\renai-chat-v1.0\libs\pythonlib\lib\site-packages (1.23.0)
INFO:chatbot.model:Loading tokenizer for chatbot_models/pygmalion-1.3b
INFO:chatbot.model:Loading the chatbot_models/pygmalion-1.3b model

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
Error no kernel image is available for execution on the device at line 479 in file D:\ai\tool\bitsandbytes\csrc\ops.cu
```

when i use RWKV-4-Pile-1B5-20220929-ctx4096.pth. when I open run.bat
it show:

```
Requirement already satisfied: numpy==1.23.0 in d:\renai-chat-v1.0\libs\pythonlib\lib\site-packages (1.23.0)
INFO:chatbot.model:Loading tokenizer for chatbot_models/RWKV-4-Pile-1B5-20220929-ctx4096.pth
Traceback (most recent call last):
  File "D:\RenAI-Chat-v1.0\libs\pythonlib\lib\site-packages\huggingface_hub\utils\_errors.py", line 264, in hf_raise_for_status
    response.raise_for_status()
  File "D:\RenAI-Chat-v1.0\libs\pythonlib\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/chatbot_models/RWKV-4-Pile-1B5-20220929-ctx4096.pth/resolve/main/tokenizer_config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\RenAI-Chat-v1.0\libs\pythonlib\lib\site-packages\transformers\utils\hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "D:\RenAI-Chat-v1.0\libs\pythonlib\lib\site-packages\huggingface_hub\utils\_validators.py", line 124, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\RenAI-Chat-v1.0\libs\pythonlib\lib\site-packages\huggingface_hub\file_download.py", line 1106, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "D:\RenAI-Chat-v1.0\libs\pythonlib\lib\site-packages\huggingface_hub\utils\_validators.py", line 124, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\RenAI-Chat-v1.0\libs\pythonlib\lib\site-packages\huggingface_hub\file_download.py", line 1441, in get_hf_file_metadata
    hf_raise_for_status(r)
  File "D:\RenAI-Chat-v1.0\libs\pythonlib\lib\site-packages\huggingface_hub\utils\_errors.py", line 306, in hf_raise_for_status
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-641315af-40c0ff005a371bc8668ddd0d)

Repository Not Found for url: https://huggingface.co/chatbot_models/RWKV-4-Pile-1B5-20220929-ctx4096.pth/resolve/main/tokenizer_config.json.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 54, in <module>
    chat_model, tokenizer = build_model_and_tokenizer_for(model_name)
  File "D:\RenAI-Chat-v1.0\chatbot\model.py", line 22, in build_model_and_tokenizer_for
    tokenizer = transformers.AutoTokenizer.from_pretrained(model_name)
  File "D:\RenAI-Chat-v1.0\libs\pythonlib\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 598, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "D:\RenAI-Chat-v1.0\libs\pythonlib\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 442, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "D:\RenAI-Chat-v1.0\libs\pythonlib\lib\site-packages\transformers\utils\hub.py", line 424, in cached_file
    raise EnvironmentError(
OSError: chatbot_models/RWKV-4-Pile-1B5-20220929-ctx4096.pth is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `use_auth_token` or log in with `huggingface-cli login` and pass `use_auth_token=True`.
```

In the tutorial you said that you can download the model directly and put it in the directory. Why does it come and ask me for these files?

**Comment by Rubiksman78** [comment]
For the first one, you can follow #6 and for the second one it's because RWKV models work differently than already existing ones on HuggingFace, only the weights are available and you need to have different scripts for using them.
